{
  "openapi": "3.0.0",
  "paths": {
    "/users": {
      "get": {
        "operationId": "AppController_getUsers",
        "summary": "Get all users",
        "parameters": [],
        "responses": {
          "200": {
            "description": "List of users"
          }
        },
        "tags": [
          "Users"
        ]
      }
    },
    "/users/{id}": {
      "get": {
        "operationId": "AppController_create",
        "summary": "Get user by ID",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User retrieved with ID"
          }
        },
        "tags": [
          "Users"
        ]
      }
    },
    "/metrics": {
      "get": {
        "operationId": "PrometheusController_index",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  },
  "info": {
    "title": "Users API",
    "description": "All public endpoints for the Users API",
    "version": "1.0",
    "contact": {}
  },
  "tags": [],
  "servers": [
    {
      "url": "http://localhost:4000",
      "description": "Local development server"
    },
    {
      "url": "http://localhost:56207",
      "description": "Local K8S development server"
    }
  ],
  "components": {
    "schemas": {}
  }
}