apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: users-api
  description: The Users API
  tags:
    - users
  links:
    - url: https://github.com/efalisotamerat/hello-nestjs
      title: GitHub Repo
      icon: github
    - url: https://github.com/efalisotamerat/hello-nestjs/blob/main/openapi.yaml
      title: API Spec
      icon: code
  annotations:
    github.com/project-slug: efalisotamerat/hello-nestjs
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
    backstage.io/techdocs-ref: dir:.
    grafana/overview-dashboard: 'http://localhost:3333/d/PTSqcpJWk/users-api-dashboard'
    grafana/dashboard-selector: 'users-api'
    grafana/alert-label-selector: 'alert=user_not_found'
    grafana/tag-selector: 'app=users-api'
    backstage.io/kubernetes-id: 'users-api'
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: 'app=users-api'
spec:
  type: openapi
  lifecycle: experimental
  owner: developers
  definition:
    $text: ./openapi.yaml
