apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: users-api
  description: The Users API
  tags:
    - nonsens
  links:
    - url: https://github.com/efalisotamerat/hello-nestjs
      title: GitHub Repo
      icon: github
    - url: https://github.com/efalisotamerat/hello-nestjs/blob/main/oa.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  definition:
    $text: ./oa.yaml
