apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  type: NodePort
  selector:
    app: hello-nestjs
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001
