prometheus:
  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  nodeExporter:
    enabled: false

grafana:
  grafana.ini:
    security:
      allow_embedding: true
    server:
      cookie_samesite: none
      cookie_secure: true
  service:
    type: NodePort
